// ============================================================================
// SHARED  —  GLB MODEL LOADING
// The poly.pizza models in ../assets/models are authored at wildly different
// scales (the crutches are 167000 units tall) and sit at arbitrary origins, so
// every model is fitted to a real-world size and grounded before it is used.
// Contract:  Assets.init(THREE, GLTFLoader) -> Assets.preload(keys) -> Promise
//            Assets.make(key)      -> a fresh Object3D at origin, or null
//            Assets.footprint(key)  -> { x, z, r } in metres, or null
// ============================================================================

const Assets = (() => {
  const DIR = '../assets/models/';

  // size = target metres along `fit` (default 'y'); yaw = baked-in facing fix.
  const CATALOG = {
    ambulance:        { file: 'ambulance.glb',        size: 2.6 },
    bandage:          { file: 'bandage.glb',          size: 0.12, fit: 'max' },
    bedside_table:    { file: 'bedside_table.glb',    size: 0.7 },
    biohazard_bin_1:  { file: 'biohazard_bin_1.glb',  size: 0.8 },
    biohazard_bin_2:  { file: 'biohazard_bin_2.glb',  size: 0.7 },
    crutches:         { file: 'crutches.glb',         size: 1.4 },
    desk_chair:       { file: 'desk_chair.glb',       size: 1.0 },
    doctor:           { file: 'doctor.glb',           size: 1.75 },
    door:             { file: 'door.glb',             size: 2.1 },
    exit_sign:        { file: 'exit_sign.glb',        size: 0.25 },
    extinguisher:     { file: 'extinguisher.glb',     size: 0.65 },
    first_aid:        { file: 'first_aid.glb',        size: 0.35 },
    gurney:           { file: 'gurney.glb',           size: 1.0,  yaw: Math.PI / 2 },
    hospital_sign:    { file: 'hospital_sign.glb',    size: 0.8 },
    patient_bed_1:    { file: 'patient_bed_1.glb',    size: 0.8 },
    patient_bed_2:    { file: 'patient_bed_2.glb',    size: 0.8 },
    pill_bottle:      { file: 'pill_bottle.glb',      size: 0.12 },
    privacy_curtain:  { file: 'privacy_curtain.glb',  size: 2.4 },
    reception_bell:   { file: 'reception_bell.glb',   size: 0.12 },
    // ER staff, generated by tools/make_staff_models.mjs — already authored at
    // human scale and facing +z, so the sizes below only vary their height.
    staff_doctor:     { file: 'staff_doctor.glb',     size: 1.78 },
    staff_nurse:      { file: 'staff_nurse.glb',      size: 1.68 },
    staff_surgeon:    { file: 'staff_surgeon.glb',    size: 1.75 },
    stethoscope:      { file: 'stethoscope.glb',      size: 0.4,  fit: 'max' },
    syringe:          { file: 'syringe.glb',          size: 0.18 },
    triage_cot_1:     { file: 'triage_cot_1.glb',     size: 1.8,  fit: 'z' },
    triage_cot_2:     { file: 'triage_cot_2.glb',     size: 1.8,  fit: 'z' },
    vending:          { file: 'vending.glb',          size: 1.9 },
    vitals_monitor_1: { file: 'vitals_monitor_1.glb', size: 0.4 },
    vitals_monitor_2: { file: 'vitals_monitor_2.glb', size: 0.4 },
    waiting_chair_1:  { file: 'waiting_chair_1.glb',  size: 0.9 },
    waiting_chair_2:  { file: 'waiting_chair_2.glb',  size: 0.7 },
    wheelchair:       { file: 'wheelchair.glb',       size: 1.1 },
  };

  let THREE = null, loader = null;
  const models = new Map();          // key -> { proto, size:Vector3 }
  const inflight = new Map();        // key -> Promise (dedupe overlapping loads)
  const failed = [];

  function init(three, GLTFLoader) {
    THREE = three;
    loader = new GLTFLoader();
  }

  // Fit to size, centre on x/z, sit the base on y=0, and bake the facing fix.
  // Two nested groups so callers can set position and rotation.y on the result
  // without the normalisation offsets rotating along with them.
  function normalise(scene, spec) {
    const box = new THREE.Box3().setFromObject(scene);
    const dim = box.getSize(new THREE.Vector3());
    const ref = spec.fit === 'max' ? Math.max(dim.x, dim.y, dim.z) : dim[spec.fit || 'y'];
    const s = ref > 1e-6 ? spec.size / ref : 1;

    scene.scale.setScalar(s);
    scene.position.set(
      -(box.min.x + dim.x / 2) * s,
      -box.min.y * s,
      -(box.min.z + dim.z / 2) * s);
    scene.traverse(o => { if (o.isMesh) { o.castShadow = true; o.receiveShadow = true; } });

    const spin = new THREE.Group(); spin.rotation.y = spec.yaw || 0; spin.add(scene);
    const root = new THREE.Group(); root.add(spin);
    return { root, size: dim.multiplyScalar(s) };
  }

  function load(key) {
    if (models.has(key)) return Promise.resolve();
    if (inflight.has(key)) return inflight.get(key);
    const spec = CATALOG[key];
    if (!spec) { failed.push(key); return Promise.resolve(); }
    const p = new Promise(resolve => {
      loader.load(DIR + spec.file, gltf => {
        const { root, size } = normalise(gltf.scene, spec);
        models.set(key, { proto: root, size });
        inflight.delete(key);
        resolve();
      }, undefined, err => {
        console.warn('[assets] failed:', spec.file, err?.message || err);
        failed.push(key);
        inflight.delete(key);
        resolve();                       // a missing model must never block the game
      });
    });
    inflight.set(key, p);
    return p;
  }

  // Loads every key in the catalog unless a subset is given. Never rejects.
  function preload(keys) {
    return Promise.all((keys || Object.keys(CATALOG)).map(load))
      .then(() => ({ loaded: models.size, failed: failed.slice() }));
  }

  function make(key) {
    const m = models.get(key);
    if (!m) return null;
    const o = m.proto.clone(true);      // geometry and materials stay shared
    o.name = key;
    return o;
  }

  // Footprint of the fitted model: r is the radius the crowd and player steer
  // around, taken from the larger horizontal side.
  function footprint(key) {
    const m = models.get(key);
    if (!m) return null;
    return { x: m.size.x, z: m.size.z, r: Math.max(m.size.x, m.size.z) / 2 };
  }

  return { init, preload, make, footprint, CATALOG,
           get loaded() { return models.size; },
           get failed() { return failed.slice(); } };
})();
